# Generated by Django 5.1 on 2024-11-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sneaker',
            new_name='Items',
        ),
    ]
