# Generated by Django 5.1 on 2024-11-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_likes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user_id',
        ),
    ]
