# Generated by Django 5.1 on 2024-11-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_items_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
